routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
  return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'before' => 'admin'], function () {
  Route::get('/', 'HomeController@index');
  Route::resource('/kelurahan', 'KelurahanController');
  Route::resource('/pasien', 'PasienController');
  Route::resource('/users', 'UsersController');
});

Route::group(['prefix' => 'datatables', 'before' => 'datatables'], function () {
  Route::get('/', ['as' => 'datatables.index', 'uses' => 'DatatablesController@index']);
  Route::get('users', ['as' => 'datatables.users', 'uses' => 'DatatablesController@users']);
  Route::get('kelurahan', ['as' => 'datatables.kelurahan', 'uses' => 'DatatablesController@kelurahan']);
  Route::get('pasien', ['as' => 'datatables.pasien', 'uses' => 'DatatablesController@pasien']);
});

app/Kelurahan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kelurahan extends Model
{
  protected $table    = 'kelurahan';
  protected $fillable = ['kelurahan', 'kecamatan', 'kota'];
  public function pasiens()
  {
    return $this->hasMany('App\Pasien');
  }
}

app/Http/Controllers/KelurahanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Kelurahan;

class KelurahanController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $kelurahan = Kelurahan::all();
    return view('kelurahan.index', compact('kelurahan'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('kelurahan.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $this->validate($request, [
      'kelurahan' => 'required',
      'kecamatan' => 'required',
      'kota'      => 'required',
    ]);

    $kelurahan = Kelurahan::create($request->all());

    if ($kelurahan->save()) {
      return redirect()->route('kelurahan.index')->with('flash-success', 'Data berhasil disimpan.');
    }

    return redirect()->back()->withErrors($kelurahan->getErrors())->withInput();return $request->all();
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $kelurahan = Kelurahan::find($id);
    return view('kelurahan.edit', compact('kelurahan'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $kelurahan = Kelurahan::find($id);
    $kelurahan->update($request->all());
    return redirect()->route('kelurahan.index')->with('flash-success', 'Data berhasil disimpan.');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    $kelurahan = Kelurahan::find($id);
    if ($kelurahan->delete()) {
      return redirect()->route('kelurahan.index')->with('flash-success', 'Data berhasil dihapus.');
    } else {
      return redirect()->route('kelurahan.index')->with('flash-errors', 'Data gagal dihapus.');
    }
  }
}

resources/views/kelurahan/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Kelurahan')

@section('content_header')
    <h1>Create Kelurahan</h1>
@stop

@section('content')
<form action="{{ route('kelurahan.store') }}" method="post">
    {!! csrf_field() !!}

    <div class="form-group has-feedback {{ $errors->has('kelurahan') ? 'has-error' : '' }}">
        <label for="kelurahan">Kelurahan</label>
        <input type="text" name="kelurahan" class="form-control" value="{{ old('kelurahan') }}">
        @if ($errors->has('kelurahan'))
            <span class="help-block">
                <strong>{{ $errors->first('kelurahan') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('kecamatan') ? 'has-error' : '' }}">
        <label for="kecamatan">Kecamatan</label>
        <input type="text" name="kecamatan" class="form-control" value="{{ old('kecamatan') }}">
        @if ($errors->has('kecamatan'))
            <span class="help-block">
                <strong>{{ $errors->first('kecamatan') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('kota') ? 'has-error' : '' }}">
        <label for="kota">Kota</label>
        <input type="text" name="kota" class="form-control" value="{{ old('kota') }}">
        @if ($errors->has('kota'))
            <span class="help-block">
                <strong>{{ $errors->first('kota') }}</strong>
            </span>
        @endif
    </div>
    <button type="submit" class="btn btn-primary btn-block btn-flat">Save</button>
</form>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/kelurahan/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Kelurahan')

@section('content_header')
    <h1>Edit Kelurahan</h1>
@stop

@section('content')
<form action="{{ route('kelurahan.update', $kelurahan->id) }}" method="post">
    {!! csrf_field() !!}
    <input type="hidden" name="_method" value="put">
    
    <div class="form-group has-feedback {{ $errors->has('kelurahan') ? 'has-error' : '' }}">
        <input type="text" name="kelurahan" class="form-control" value="{{ $kelurahan->kelurahan }}">
        @if ($errors->has('kelurahan'))
            <span class="help-block">
                <strong>{{ $errors->first('kelurahan') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('kecamatan') ? 'has-error' : '' }}">
        <input type="text" name="kecamatan" class="form-control" value="{{ $kelurahan->kecamatan }}">
        @if ($errors->has('kecamatan'))
            <span class="help-block">
                <strong>{{ $errors->first('kecamatan') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('kota') ? 'has-error' : '' }}">
        <input type="text" name="kota" class="form-control" value="{{ $kelurahan->kota }}">
        @if ($errors->has('kota'))
            <span class="help-block">
                <strong>{{ $errors->first('kota') }}</strong>
            </span>
        @endif
    </div>
    <button type="submit" class="btn btn-primary btn-block btn-flat">Save</button>
</form>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/kelurahan/index.blade.php
@extends('adminlte::page')

@section('title', 'Kelurahan')

@section('content_header')
    <h1>Data Kelurahan</h1>
@stop

@section('content')
@can('user-admin')
  <a href="{{ route('kelurahan.create') }}" class="btn btn-primary btn-md">Create Kelurahan</a>
@endcan
<table class="table table-striped table-hover table-bordered" id="kelurahan-table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Kelurahan</th>
      <th>Kecamatan</th>
      <th>Kota</th>
      <th>Created At</th>
      <th></th>
    </tr>
  </thead>
</table>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@push('js')
<script>
$(function() {
    $('#kelurahan-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('datatables.kelurahan') !!}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'kelurahan', name: 'kelurahan' },
            { data: 'kecamatan', name: 'kecamatan' },
            { data: 'kota', name: 'kota' },
            { data: 'created_at', name: 'created_at' },
            { data: 'actions', name: 'actions' }
        ]
    });
});
</script>
@endpush