routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
  return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'before' => 'admin'], function () {
  Route::get('/', 'HomeController@index');
  Route::resource('/kelurahan', 'KelurahanController');
  Route::resource('/pasien', 'PasienController');
  Route::resource('/users', 'UsersController');
});

Route::group(['prefix' => 'datatables', 'before' => 'datatables'], function () {
  Route::get('/', ['as' => 'datatables.index', 'uses' => 'DatatablesController@index']);
  Route::get('users', ['as' => 'datatables.users', 'uses' => 'DatatablesController@users']);
  Route::get('kelurahan', ['as' => 'datatables.kelurahan', 'uses' => 'DatatablesController@kelurahan']);
  Route::get('pasien', ['as' => 'datatables.pasien', 'uses' => 'DatatablesController@pasien']);
});

app/Pasien.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pasien extends Model
{
  protected $table    = 'pasien';
  protected $fillable = ['nama', 'alamat', 'no_telp', 'rt_rw', 'kelurahan_id', 'tanggal_lahir', 'jenis_kelamin'];
  public function kelurahan()
  {
    return $this->belongsTo('App\Kelurahan');
  }
}

app/Http/Controllers/PasienController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Kelurahan;
use \App\Pasien;

class PasienController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $pasiens = Pasien::all();
    return view('pasien.index', compact('pasiens'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    $kelurahan = Kelurahan::all();
    return view('pasien.create', compact('kelurahan'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $this->validate($request, [
      'nama'          => 'required',
      'alamat'        => 'required',
      'no_telp'       => 'required',
      'rt_rw'         => 'required',
      'tanggal_lahir' => 'required',
      'jenis_kelamin' => 'required',
    ]);
    $ym          = \Carbon\Carbon::now()->format('ym');
    $last_pasien = Pasien::orderBy('created_at', 'desc')->first();
    if ($ym == substr($last_pasien->id_pasien, 0, 4)) {
      $new_id = (int) substr($last_pasien->id_pasien, 4) + 1;
      if (strlen($new_id) == 1) {
        $new_id = '00000' . $new_id;
      } elseif (strlen($new_id) == 2) {
        $new_id = '0000' . $new_id;
      } elseif (strlen($new_id) == 3) {
        $new_id = '000' . $new_id;
      } elseif (strlen($new_id) == 4) {
        $new_id = '00' . $new_id;
      } elseif (strlen($new_id) == 5) {
        $new_id = '0' . $new_id;
      }
      $new_id = $ym . $new_id;
    } else {
      $new_id = $ym . '000001';
    }

    $pasien                = new Pasien;
    $pasien->nama          = $request->nama;
    $pasien->alamat        = $request->alamat;
    $pasien->no_telp       = $request->no_telp;
    $pasien->rt_rw         = $request->rt_rw;
    $pasien->kelurahan_id  = $request->kelurahan_id;
    $pasien->tanggal_lahir = $request->tanggal_lahir;
    $pasien->jenis_kelamin = $request->jenis_kelamin;
    $pasien->id_pasien     = (int) $new_id;

    if ($pasien->save()) {
      return redirect()->route('pasien.index')->with('flash-success', 'Data berhasil disimpan.');
    }

    return redirect()->back()->withErrors($pasien->getErrors())->withInput();return $request->all();
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $pasien    = Pasien::find($id);
    $kelurahan = Kelurahan::all();
    return view('pasien.edit', compact('pasien', 'kelurahan'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $pasien = Pasien::find($id);
    $pasien->update($request->all());
    return redirect()->route('pasien.index')->with('flash-success', 'Data berhasil disimpan.');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    $pasien = Pasien::find($id);
    if ($pasien->delete()) {
      return redirect()->route('pasien.index')->with('flash-success', 'Data berhasil dihapus.');
    } else {
      return redirect()->route('pasien.index')->with('flash-errors', 'Data gagal dihapus.');
    }
  }
}

resources/views/pasien/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Pasien')

@section('content_header')
    <h1>Create Pasien</h1>
@stop

@section('content')
<form action="{{ route('pasien.store') }}" method="post">
    {!! csrf_field() !!}

    <div class="form-group has-feedback {{ $errors->has('nama') ? 'has-error' : '' }}">
        <label for="nama">Nama</label>
        <input type="text" name="nama" class="form-control" value="{{ old('nama') }}">
        @if ($errors->has('nama'))
            <span class="help-block">
                <strong>{{ $errors->first('nama') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('alamat') ? 'has-error' : '' }}">
        <label for="alamat">Alamat</label>
        <textarea name="alamat" id="alamat" class="form-control">{{ old('alamat') }}</textarea>
        @if ($errors->has('alamat'))
            <span class="help-block">
                <strong>{{ $errors->first('alamat') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('no_telp') ? 'has-error' : '' }}">
        <label for="no_telp">No Telepon</label>
        <input type="text" name="no_telp" class="form-control" value="{{ old('no_telp') }}">
        @if ($errors->has('no_telp'))
            <span class="help-block">
                <strong>{{ $errors->first('no_telp') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('rt_rw') ? 'has-error' : '' }}">
        <label for="rt_rw">RT/RW</label>
        <input type="text" name="rt_rw" class="form-control" value="{{ old('rt_rw') }}">
        @if ($errors->has('rt_rw'))
            <span class="help-block">
                <strong>{{ $errors->first('rt_rw') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('kelurahan_id') ? 'has-error' : '' }}">
        <label for="kelurahan_id">Kelurahan</label>
        <select name="kelurahan_id" id="kelurahan_id" class="form-control">
            @if ($kelurahan->count() > 0)
                @foreach ($kelurahan as $value)
                    <option value="{{ $value->id }}">{{ $value->kelurahan.' - '.$value->kecamatan.', '.$value->kota }}</option>
                @endforeach
            @else
                <option value="0">no data</option>
            @endif
        </select>
        @if ($errors->has('kelurahan_id'))
            <span class="help-block">
                <strong>{{ $errors->first('kelurahan_id') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('tanggal_lahir') ? 'has-error' : '' }}">
        <label for="tanggal_lahir">Tanggal Lahir</label>
        <input type="date" name="tanggal_lahir" class="form-control" value="{{ old('tanggal_lahir') }}">
        @if ($errors->has('tanggal_lahir'))
            <span class="help-block">
                <strong>{{ $errors->first('tanggal_lahir') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('jenis_kelamin') ? 'has-error' : '' }}">
        <label for="jenis_kelamin">Jenis Kelamin</label>
        <select name="jenis_kelamin" id="jenis_kelamin" class="form-control">
            <option value="Pria">Pria</option>
            <option value="Wanita">Wanita</option>
        </select>
        @if ($errors->has('jenis_kelamin'))
            <span class="help-block">
                <strong>{{ $errors->first('jenis_kelamin') }}</strong>
            </span>
        @endif
    </div>
    <button type="submit" class="btn btn-primary btn-block btn-flat">Save</button>
</form>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/pasien/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Pasien')

@section('content_header')
    <h1>Edit Pasien</h1>
@stop

@section('content')
<form action="{{ route('pasien.update', $pasien->id) }}" method="post">
    {!! csrf_field() !!}
    <input type="hidden" name="_method" value="put">

    <div class="form-group has-feedback {{ $errors->has('nama') ? 'has-error' : '' }}">
        <label for="nama">Nama</label>
        <input type="text" name="nama" class="form-control" value="{{ $pasien->nama }}">
        @if ($errors->has('nama'))
            <span class="help-block">
                <strong>{{ $errors->first('nama') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('alamat') ? 'has-error' : '' }}">
        <label for="alamat">Alamat</label>
        <textarea name="alamat" id="alamat" class="form-control">{{ $pasien->alamat }}</textarea>
        @if ($errors->has('alamat'))
            <span class="help-block">
                <strong>{{ $errors->first('alamat') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('no_telp') ? 'has-error' : '' }}">
        <label for="no_telp">No Telepon</label>
        <input type="text" name="no_telp" class="form-control" value="{{ $pasien->no_telp }}">
        @if ($errors->has('no_telp'))
            <span class="help-block">
                <strong>{{ $errors->first('no_telp') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('rt_rw') ? 'has-error' : '' }}">
        <label for="rt_rw">RT/RW</label>
        <input type="text" name="rt_rw" class="form-control" value="{{ $pasien->rt_rw }}">
        @if ($errors->has('rt_rw'))
            <span class="help-block">
                <strong>{{ $errors->first('rt_rw') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('kelurahan_id') ? 'has-error' : '' }}">
        <label for="kelurahan_id">Kelurahan</label>
        <select name="kelurahan_id" id="kelurahan_id" class="form-control">
            @if ($kelurahan->count() > 0)
                @foreach ($kelurahan as $value)
                    <option value="{{ $value->id }}" {{ $pasien->kelurahan_id == $value->id ? 'selected' : '' }}>{{ $value->kelurahan.' - '.$value->kecamatan.', '.$value->kota }}</option>
                @endforeach
            @else
                <option value="0">no data</option>
            @endif
        </select>
        @if ($errors->has('kelurahan_id'))
            <span class="help-block">
                <strong>{{ $errors->first('kelurahan_id') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('tanggal_lahir') ? 'has-error' : '' }}">
        <label for="tanggal_lahir">Tanggal Lahir</label>
        <input type="date" name="tanggal_lahir" class="form-control" value="{{ $pasien->tanggal_lahir }}">
        @if ($errors->has('tanggal_lahir'))
            <span class="help-block">
                <strong>{{ $errors->first('tanggal_lahir') }}</strong>
            </span>
        @endif
    </div>
    <div class="form-group has-feedback {{ $errors->has('jenis_kelamin') ? 'has-error' : '' }}">
        <label for="jenis_kelamin">Jenis Kelamin</label>
        <select name="jenis_kelamin" id="jenis_kelamin" class="form-control">
            <option value="Pria" {{ $pasien->jenis_kelamin == 'Pria' ? 'selected' : '' }}>Pria</option>
            <option value="Wanita" {{ $pasien->jenis_kelamin == 'Wanita' ? 'selected' : '' }}>Wanita</option>
        </select>
        @if ($errors->has('jenis_kelamin'))
            <span class="help-block">
                <strong>{{ $errors->first('jenis_kelamin') }}</strong>
            </span>
        @endif
    </div>
    <button type="submit" class="btn btn-primary btn-block btn-flat">Save</button>
</form>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/pasien/index.blade.php
@extends('adminlte::page')

@section('title', 'Pasien')

@section('content_header')
    <h1>Data Pasien</h1>
@stop

@section('content')
<a href="{{ route('pasien.create') }}" class="btn btn-primary btn-md">Create Pasien</a>
<table class="table table-striped table-hover table-bordered" id="pasien-table">
  <thead>
    <tr>
      <th>ID Pasien</th>
      <th>Nama</th>
      <th>Alamat</th>
      <th>No Telepon</th>
      <th>RT/RW</th>
      <th>Kelurahan</th>
      <th>Tanggal Lahir</th>
      <th>Jenis Kelamin</th>
      <th></th>
    </tr>
  </thead>
</table>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@push('js')
<script>
$(function() {
    $('#pasien-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('datatables.pasien') !!}',
        columns: [
            { data: 'id_pasien', name: 'id_pasien' },
            { data: 'nama', name: 'nama' },
            { data: 'alamat', name: 'alamat' },
            { data: 'no_telp', name: 'no_telp' },
            { data: 'rt_rw', name: 'rt_rw' },
            { data: 'kel', name: 'kel' },
            { data: 'tanggal_lahir', name: 'tanggal_lahir' },
            { data: 'jenis_kelamin', name: 'jenis_kelamin' },
            { data: 'actions', name: 'actions' }
        ]
    });
});
</script>
@endpush